import re

def getUniqueItems(iterable):
    seen = set()
    result = []
    for item in iterable:
        if item not in seen:
            seen.add(item)
            result.append(item)
    return result

def sortMyLetters(iterable):
    for idx in range(len(iterable)):
        iterable[idx] = ''.join(sorted(iterable[idx])).upper()

# delete content from file
open('my-anagrams.txt', 'w').close()

file = open("text.txt", "r")
myText = file.read()
file.close()

# \W+ works with diacritics, [^a-zA-Z]+ only with latin characters
myList = re.compile(r'\W+').split(myText)

# filter() - removes empty strings from list
# list() - re-converts the iterator (generated by filter) to a list
myList = list(filter(None, myList))

# clone list without affecting the content of the original
mySortedList = list(myList)

sortMyLetters(mySortedList)

# list of indexes that would be skipped if the word was checked once
myIndexes = []

my_input = input("Enter your word here:\n")

assert my_input.isalpha(), "The input is not alpha"

# sort letters and transform to uppercase for comparison
my_input = ''.join(sorted(my_input)).upper()
count = 0
for idx in range(len(mySortedList)):

    if idx in myIndexes:
        continue

    myAnagrams = []

    for idy in range(idx, len(mySortedList)):
        if mySortedList[idx] == mySortedList[idy]:
            # count += 1
            myAnagrams.append(myList[idy])
            if idy not in myIndexes:
                myIndexes.append(idy)

    # remove duplicate elements from list
    myAnagrams = getUniqueItems(myAnagrams)

    if len(myAnagrams) > 1:

        # clone current list of anagrams
        mySortedAnagrams = list(myAnagrams)
        # sort the letters of the elements within the list
        sortMyLetters(mySortedAnagrams)

        if my_input in mySortedAnagrams:
            print("There are " + str(len(myAnagrams)) + " anagrams for your word: " + str(myAnagrams))

        # print(len(myAnagrams))
        for x in range(len(myAnagrams)):
            file = open("my-anagrams.txt", "a")
            if x == len(myAnagrams) - 1:
                file.write(str(myAnagrams[x]) + '\n')
            else:
                file.write(str(myAnagrams[x]).rstrip('\n') + ", ")
            file.close()
            # print(myAnagrams[x])




