import re

file = open("anagrams-text.txt", "r")
myText = file.read()
file.close()

myList = re.compile(r'[^a-z]+').split(myText)

# filter() - removes empty strings from list
# list() - re-converts the iterator (generated by filter) to a list
myList = list(filter(None, myList))

# my list without empty strings and words not sorted
# print(myList)

# clone list without affecting the content of the original
mySortedList = list(myList)

# sort letter in each element of the new list and to uppercase
for idx in range(len(mySortedList)):
    mySortedList[idx] = ''.join(sorted(mySortedList[idx])).upper()

# my list without empty strings and words sorted
#print(mySortedList)

# list of indexes that would be skipped if the word was checked once
myIndexes = []

for idm in range(len(mySortedList)):
    counter = 0

    for idy in range(len(mySortedList)):
        # skip this iteration if the word was checked once
        if idy in myIndexes:
            continue
        if mySortedList[idm] == mySortedList[idy]:

            counter += 1
            if counter != 0:
                print(str(idm) + " " + myList[idy] + " my index: " + str(idy) + " - counter is " + str(counter))

                file = open("my-anagrams.txt", "a")
                if counter == 1:
                    file.write("\n")
                file.write(myList[idy] + " ")
                file.close()

                if idy not in myIndexes:
                    myIndexes.append(idy)

# print(myList)
# print(sorted(myIndexes))

